// Genre mapping (English to Japanese)
export const GENRE_MAPPING = {
  'Action': 'アクション',
  'Adventure': 'アドベンチャー',
  'RPG': 'RPG',
  'Strategy': 'ストラテジー',
  'Simulation': 'シミュレーション',
  'Casual': 'カジュアル',
  'Indie': 'インディー',
  'Sports': 'スポーツ',
  'Racing': 'レーシング',
  'Massively Multiplayer': 'MMO',
  'Early Access': '早期アクセス',
  'Other': 'その他',
  'Utilities': '補助ツール',
  'Free To Play': '無料',
  'Audio Production': 'オーディオ制作',
  'Animation & Modeling': 'アニメ・モデリング',
  'Design & Illustration': 'デザイン・イラスト',
  'Education': '教育',
  'Game Development': 'ゲーム開発',
  'Gore': 'ゴア',
  'Photo Editing': '写真編集',
  'Video Production': '動画制作',
  'Web Publishing': 'Web出版'
};
